id = "dark-pop-ui"
name = "🌌 Dark Pop UI 🎨"
description = "Midnight hues with a neon twist — a dark theme that keeps your code stylish and your eyes happy."
version = "0.0.2"
schema_version = 1
authors = ["Kunal Arora <kunal_arora@live.com>"]
repository = "https://github.com/kunal-arora/zed-theme-dark-pop-ui"
